### ISSUE TITLE
Authentication to GitHub fails execting ghp-import

### ISSUE THREAD

**Issue by stuchalk** [davisp/ghp-import#112]
I have a project in PyCharm and via the command line run the recommended command for adding gh pages for jupyter-book (https://jupyterbook.org/en/stable/publish/gh-pages.html option 2) using ghp-import.  When I do this it prompts for username and password and then quits because the repo I want to install it on is not on my personal account, but on an organizational account.

![Screen Shot 2022-07-26 at 7 16 52 PM](https://user-images.githubusercontent.com/540150/181128557-b21dadc8-1c21-46b8-ac99-4f2f6b4c09bc.jpg)

As you can see it tries 'https://github.com/stuchalk/WFChemCookbook.git/' but the repo is actually at ''https://github.com/iupac/WFChemCookbook.git/'.

How do I get ghp-import to allow me to authenticate to an organization?

**Comment by c-w** [comment]
ghp_import isn’t doing anything interesting with authentication so I’d assume that this is a problem linked to the configuration of the underlying remote. From the screenshot it looks like you’re using https to do the push with an account password which is a feature that was removed from GitHub recently ([see changelog](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/)). Try using a personal access token or SSH key instead of the password as described [here](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/#what-you-need-to-do-today).

**Comment by c-w** [comment]
@stuchalk Closing this as I haven't heard back in a while. Feel free to re-open if this is still an issue for you :raised_hands:
