### ISSUE TITLE
check if content has changed

### ISSUE THREAD

**Issue by bbinet** [davisp/ghp-import#2]
Thanks for ghp-import, this greatly simplifies update of the gh-pages branch!

The last thing I miss is a way to prevent ghp-import to commit and push if the output have not changed.
For example I'm using ghp-import in a post-commit hook to update the doc on every commit. So currently ghp-import push a new commit (often empty) to the gh-pages branch for _every_ commits even those that don't change the output documentation.

**Comment by dhimmel** [comment]
This would be similar to the [Travis CI option](https://docs.travis-ci.com/user/deployment/pages/) for `allow_empty_commit`. Note I still use `ghp-import` over the Travis GitHub Pages Deployment because the later [requires](https://github.com/travis-ci/travis-ci/issues/9213#issuecomment-508148288) unnecessary credentials
