### ISSUE TITLE
raw date crash

### ISSUE THREAD

**Issue by aaa34169** [davisp/ghp-import#60]
Hi

does anyone get a invalid raw date error
![2017-01-23 13_28_18-output](https://cloud.githubusercontent.com/assets/3098117/22205719/f71b25b6-e16f-11e6-9233-e07b56b65634.png)

i have no idea how to fix that

**Comment by davisp** [comment]
Odd, can you show what you get from running this in the python prompt?

```python
import time
print time.strftime('%z')
```

I'm guessing its giving you "GMT Standard Time" which should theoretically be a number like -0:00. Assuming that's what it is you'll want to either figure out how to make your `time.strftime('%z')` call return an appropriate timezone offset instead of a random string name.

**Comment by mikofski** [comment]
The issue is that the OP and myself are using Python-2.7 not Python-3.x in which the lower case `'%z'` escape is not guaranteed to return the hour offset. See this [SO answer](http://stackoverflow.com/a/26369814/1020470) and the [footnote in the Python-2 docs for `time`](https://docs.python.org/2/library/time.html#id2).

The solutions are:
1. use Python-3 instead of Python-3
2. send a PR to this repo, to change [L120](../blob/ee9d8f0/ghp_import.py#L120) to:

    currtz = datetime.now(tz.tzlocal()).strftime('%z')

works for both versions of Python on all platforms (win32, darwin, linux2).

**Comment by osinimu** [comment]
Did this work? Having a similar issue 
![capture](https://user-images.githubusercontent.com/13364447/40886280-a85ad4aa-672c-11e8-9be5-0da372b1b4a2.PNG)

**Comment by mikofski** [comment]
But @osinimu you are still using Python-2.7, not Python-3. Can you please try Python-3? You can install [Python-3.6](https://www.python.org/downloads/) [side-by-side with Python-2.7](https://stackoverflow.com/a/17954487/1020470), use [virtualenv](https://pypi.org/project/virtualenv/) in either Python 2 _or_ 3 to [create a Python-3 virtual environment](https://virtualenv.pypa.io/en/stable/reference/#cmdoption-p), and then just install the packages you need for Pelican.

    ~/osinimu (pelican) $ virtualenv -p /c/Program\ Files/Python36/python.exe venv3
    ~/osinimu (pelican) $ source venv3/bin/activate
    (venv3) ~/osinimu (pelican) $ pip install pelican ghp-import

**Comment by c-w** [comment]
This has been released in [0.6.0](https://pypi.org/project/ghp-import/0.6.0/).
